# client.yaml
client:
  personal:
    id: ""
    name: ""
    email: ""
    password: ""

  # Environment in which the client is operating (e.g., development, production)
  environment: "local"

  # API connection settings
  api:
    base_url: "https://jcloud.up.railway.app"
    auth_token: ""
    timeout: 30
    retries: 5
    ssl_verify: true

  logging:
    level: "info"
    log_path: "/var/log/client_app.log"
    max_size: 100
    max_files: 3

hints:
  # Configuration hints
  config:
    add.emptyPath: true
    add.loginRequired: true
    add.noFilesMatched: true
    add.allFlagMissing: true
    add.noModifiedFiles: true
    add.dryRunWithoutFiles: true
    add.excludeNotMatched: true
    add.unmodifiedWithUpdate: true

    login.loginRequired: true
    login.invalidCredentials: true

    global.unknownCommand: true
    global.flagNotRecognized: true
    global.noArgsProvided: true
    global.missingFileOrDirectory: true
    global.missingRequiredFlag: true

  # Command hints
  commands:
      add.emptyPath:
        message: "Nothing specified, nothing added."
        hint:
          - "Maybe you wanted to say 'jcloud add .'?"
          - "Disable this hint with 'jcloud config hints.add.emptyPath false'."
      add.loginRequired:
        message: "You must log in before using this command."
        hint:
          - "Use 'jcloud login [username] [email] [password]' to log in first."
          - "Disable this hint with 'jcloud config hints.add.loginRequired false'."
      add.noFilesMatched:
        message: "No files were added."
        hint:
          - "Make sure the file paths are correct."
          - "Use 'jcloud add --force' to include hidden files."
          - "Disable this hint with 'jcloud config hints.add.noFilesMatched false'."
      add.allFlagMissing:
        message: "It looks like you want to add all files."
        hint:
          - "Try 'jcloud add --all' to add all files in the current directory."
          - "Disable this hint with 'jcloud config hints.add.allFlagMissing false'."
      add.noModifiedFiles:
        message: "No modified files found to update."
        hint:
          - "Ensure your files have been modified since last addition."
          - "Use 'jcloud add' without '--update' to add all files."
          - "Disable this hint with 'jcloud config hints.add.noModifiedFiles false'."
      add.dryRunWithoutFiles:
        message: "Dry run requested, but no files specified."
        hint:
          - "Use 'jcloud add --dry-run .' to simulate adding all files."
          - "Disable this hint with 'jcloud config hints.add.dryRunWithoutFiles false'."
      add.excludeNotMatched:
        message: "No files matched the exclusion pattern."
        hint:
          - "Ensure your exclusion pattern is correct, e.g., 'jcloud add --exclude \"*.log\"."
          - "Disable this hint with 'jcloud config hints.add.excludeNotMatched false'."
      add.unmodifiedWithUpdate:
        message: "No modified files found to add with --update."
        hint:
          - "Make sure you have modified the files or use 'jcloud add' without '--update' to include all files."
          - "Disable this hint with 'jcloud config hints.add.unmodifiedWithUpdate false'."

      login.loginRequired:
        message: "You must log in before using this command."
        hint:
          - "Use 'jcloud login [username] [email] [password]' to log in first."
          - "If you don't have an account, create one with 'jcloud register'."
      login.invalidCredentials:
        message: "Invalid login credentials provided."
        hint:
          - "Ensure your username, email, and password are correct."
          - "You can reset your password if forgotten."

      global.unknownCommand:
        message: "Unknown command."
        hint:
          - "Use 'jcloud --help' to see a list of available commands."
      global.flagNotRecognized:
        message: "Unrecognized flag or option."
        hint:
          - "Check available flags with 'jcloud [command] --help'."
      global.noArgsProvided:
        message: "No arguments provided."
        hint:
          - "Use 'jcloud [command] --help' to see how to use this command properly."
      global.missingFileOrDirectory:
        message: "No file or directory specified."
        hint:
          - "Try 'jcloud add [file]' to add specific files."
          - "Use 'jcloud add --all' to add all files in the current directory."
      global.missingRequiredFlag:
        message: "Missing required flag."
        hint:
          - "Check available flags with 'jcloud [command] --help'."
          - "Make sure to specify all required flags."


# Connection settings to external services (e.g., databases, message brokers)
services:
  database:
    host: "db.example.com"
    port: 5432
    username: "dbuser"
    password: "dbpass"
    database: "client_db"
    sslmode: "require" # options: disable, require, verify-ca, verify-full

  cache:
    host: "cache.example.com"
    port: 6379
    use_ssl: false

  message_broker:
    host: "broker.example.com"
    port: 5672
    queue_name: "client_queue"
    username: "brokeruser"
    password: "brokerpass"
    use_ssl: true

# Retry strategy in case of failures
retry_strategy:
  max_attempts: 5
  delay_seconds: 2
  backoff_multiplier: 1.5

# Optional metrics and monitoring settings
metrics:
  enabled: true
  provider: "prometheus"
  endpoint: "http://metrics.example.com"
  interval_seconds: 60
