env: "local" #changable to debug or prod or local

server:
  address: ":8080"
  readTimeout: 10s
  writeTimeout: 20s
  idleTimeout: 60s

database:
  driverName: "sqlite3"
  dataSourceName: "file::memory:?cache=shared"

url: "https://cloudfiles.up.railway.app"
