env: "local" #changable to debug or prod

server:
  address: ":8080"
  readTimeout: 10s
  writeTimeout: 20s
  idleTimeout: 60s

database:
  driverName: "sqlite3"
  dataSourceName: "../../storage/storage.db"

url: "https://cloudfiles.up.railway.app"
