name: Qodana

on:
  push:
    branches:
      - example

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@latest
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          results-dir: ./qodana/results
          cache-dir: ./qodana/caches